before_script:
  - npm config set cache /tmp/npmcache

stages:
  - build
  - test
  - deploy

install:
  stage: build
  script:
    - npm install
  tags:
    - shell
    - mac

npmtest:
  stage: test
  script:
    - npm install
    - npm test
  tags:
    - shell
    - mac

kanban:
  stage: deploy
  script:
    - echo "hey…"
  tags:
    - shell
    - mac